import './globals.css'

export const metadata = {
  title: 'Gaybe Safe Haven',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav>
          about
          list
          add a shelter
          public api
        </nav>
        {children}
      </body>
    </html>
  )
}
