name: cypress-tests CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cypress-run:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/Checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with: 
          build: npm run build
          start: npm start 
          test: npm run cypress
          config-file: cypress.config.js
